name Maven Build & Sonar analysis

on
  push
    branches
      - main
  pull_request
    types [opened, synchronize, reopened]

jobs

  build
    name  build main branch
    runs-on ubuntu-latest
    steps
      - uses actionscheckout@v2
      - uses actionssetup-java@v2
        with
          distribution 'adopt' # See 'Supported distributions' for available options
          java-version '17'

      - name Maven Build & Sonar analysis
        #run mvn -B verify org.sonarsource.scanner.mavensonar-maven-pluginsonar -Dsonar.projectKey=univ-smb-m1-isc-2021_hello-world
        run mvn -B verify --file pom.xml
        env
          GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN ${{ secrets.SONAR_TOKEN }}